/*Per evitare problemi durante la creazione delle tabelle, è consigliato crearle nell'rdine una alla volta*/

/*CREAZIONE DATABASE*/

--create database if not exists ProgettoOOBD;

/*DEFINIZIONE TABELLE*/

CREATE TABLE IF NOT EXISTS GRUPPI
(
	Nome VARCHAR NOT NULL PRIMARY KEY
);	

CREATE TABLE IF NOT EXISTS CASSAFORTE
(
	PasswordCF VARCHAR NOT NULL PRIMARY KEY
);	

CREATE TABLE IF NOT EXISTS  CONTATTO 
(
	CONTATTO_ID SERIAL PRIMARY KEY,
	PREFISSO_NOME VARCHAR,
	NOME VARCHAR NOT NULL,
	COGNOME VARCHAR,
	PATH_FOTO VARCHAR,
	Password_cassaforte VARCHAR,
	CONSTRAINT Cassaforte_FK FOREIGN KEY(Password_cassaforte) REFERENCES CASSAFORTE(PasswordCF)
	on delete set null on update cascade
);

CREATE TABLE IF NOT EXISTS MAIL
(
	INDIRIZZO_EMAIL VARCHAR not null,
	Contatto_Associato Integer NOT NULL,
	CONSTRAINT Contatto_Associato_FK FOREIGN KEY(Contatto_Associato) REFERENCES Contatto(Contatto_ID)
	on delete cascade on update cascade
);

ALTER TABLE IF EXISTS public.mail
    ADD CONSTRAINT "ProprietarioMail_unique" UNIQUE (indirizzo_email, contatto_associato);

CREATE TABLE IF NOT EXISTS ACCOUNT
(
	Account_ID SERIAL NOT NULL PRIMARY KEY,
	CONTATTO_ASSOCIATO INT NOT NULL,
	FORNITORE VARCHAR NOT NULL,
	NICKNAME VARCHAR NOT NULL,
	MAIL VARCHAR NOT NULL,
	FRASE_DI_BENVENUTO VARCHAR,
	CONSTRAINT fk_ACCOUNT_Contatto FOREIGN KEY(CONTATTO_ASSOCIATO) REFERENCES CONTATTO(CONTATTO_ID)
   		ON DELETE CASCADE 	ON UPDATE Cascade
);

ALTER TABLE IF EXISTS public.account
    ALTER COLUMN mail SET DEFAULT 'Nessuna Mail';
	
CREATE TABLE IF NOT EXISTS INDIRIZZI
(
	INDIRIZZI_ID SERIAL NOT NULL Primary key,
	VIA VARCHAR NOT NULL,
	Città VARCHAR NOT NULL,
	CODICE_POSTALE VARCHAR NOT NULL,
	NAZIONE VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS NUMERI_TELEFONICI_FISSI
(
	Numero_ID Serial Primary key,
	CONTATTO_ASSOCIATO INT NOT NULL,
	PREFISSO_NAZIONALE VARCHAR NOT NULL,
	NUMERO VARCHAR NOT NULL,
	IDENTIFICATORE VARCHAR NOT NULL,
	Reindirizzamento int,
	CONSTRAINT fk_NUMERO FOREIGN KEY(CONTATTO_ASSOCIATO) REFERENCES CONTATTO(CONTATTO_ID)
   		ON DELETE CASCADE 	ON UPDATE Cascade
);

CREATE TABLE IF NOT EXISTS NUMERI_TELEFONICI_MOBILI
(
	Numero_ID Serial Primary key,
	CONTATTO_ASSOCIATO INT NOT NULL,
	PREFISSO_NAZIONALE VARCHAR NOT NULL,
	NUMERO VARCHAR NOT NULL,
	IDENTIFICATORE VARCHAR NOT NULL,
	Reindirizzamento int,
	CONSTRAINT fk_NUMERO FOREIGN KEY(CONTATTO_ASSOCIATO) REFERENCES CONTATTO(CONTATTO_ID)
   		ON DELETE CASCADE 	ON UPDATE Cascade
);

ALTER TABLE IF EXISTS numeri_telefonici_fissi
    ADD CONSTRAINT FK_Deputato_Fissi FOREIGN KEY (Reindirizzamento)
    REFERENCES numeri_telefonici_fissi (Numero_ID) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
    
    ALTER TABLE IF EXISTS numeri_telefonici_Mobili
    ADD CONSTRAINT FK_Deputato_Mobili FOREIGN KEY (Reindirizzamento)
    REFERENCES numeri_telefonici_Mobili (Numero_ID) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS ABITA(
	INDIRIZZO_ASSOCIATO INT NOT NULL, 
	CONTATTO_ASSOCIATO INT NOT NULL, 
	Abitazione_Principale BOOL NOT NULL, 
	Identificatore VARCHAR NOT NULL,
	CONSTRAINT fk_CONTATTO_ABITA FOREIGN KEY(CONTATTO_ASSOCIATO) REFERENCES CONTATTO(CONTATTO_ID)
   		ON DELETE CASCADE 	ON UPDATE Cascade,
	CONSTRAINT fk_INDIRIZZO_ABITA FOREIGN KEY(INDIRIZZO_ASSOCIATO) REFERENCES indirizzi(indirizzi_id)
	   ON DELETE CASCADE 	ON UPDATE Cascade
);

CREATE TABLE IF NOT EXISTS APPARTENENZA
(
	Gruppo_Nome VARCHAR NOT NULL, 
	Contatto_ID INT NOT NULL,
	CONSTRAINT fk_APPARTENENZA_CONTATTO FOREIGN KEY(CONTATTO_ID) REFERENCES CONTATTO(CONTATTO_ID)
   		ON DELETE CASCADE 	ON UPDATE CASCADE,
	CONSTRAINT fk_APPARTENENZA_GRUPPO FOREIGN KEY(Gruppo_Nome) REFERENCES GRUPPI(NOME)
   		ON DELETE CASCADE 	ON UPDATE CASCADE
);



ALTER TABLE IF EXISTS public.numeri_telefonici_mobili
    ADD CONSTRAINT "Unique_numero_Prefisso_Mobile" UNIQUE (contatto_associato, prefisso_nazionale, numero);
    
    
ALTER TABLE IF EXISTS public.numeri_telefonici_Fissi
    ADD CONSTRAINT "Unique_numero_Prefisso_FIsso" UNIQUE (contatto_associato, prefisso_nazionale, numero);