package Model;

public enum EnumPrefissoNumero {
	
	Afghanistan("Afghanistan +93"),
	Alaska("Alaska +1"),
	Albania("Albania +355"),
	Algeria("Algeria +213"),
	Andorra("Andorra +376"),
	Angola("Angola +244"),
	Anguilla("Anguilla +1"),
	AntiguaeBarbuda("Antigua e Barbuda +1"),
	AntilleOlandesi("Antille Olandesi +599"),
	ArabiaSaudita("Arabia Saudita +966"),
	Argentina("Argentina +54"),
	Armenia("Armenia +374"),
	Aruba("Aruba +297"),
	Ascensione("Ascensione +247"),
	Australia("Australia +61"),
	AustraliaAntartic("Australia Antartic +67210"),
	Austria("Austria +43"),
	Azerbaigian("Azerbaigian +994"),
	Bahamas("Bahamas +1"),
	Bahrein("Bahrein +973"),
	Bangladesh("Bangladesh +880"),
	Barbados("Barbados +1"),
	Belgio("Belgio +32"),
	Belize("Belize +501"),
	Benin("Benin +229"),
	Bermuda("Bermuda +1"),
	Bhutan("Bhutan +975"),
	Bielorussia("Bielorussia +375"),
	Bolivia("Bolivia +591"),
	BosniaErzegovina("Bosnia Erzegovina +387"),
	Botswana("Botswana +267"),
	Brasile("Brasile +55"),
	Brunei("Brunei +673"),
	Bulgaria("Bulgaria +359"),
	BurkinaFaso("Burkina Faso +226"),
	Burundi("Burundi +257"),
	Cambogia("Cambogia +855"),
	Camerun("Camerun +237"),
	Canada("Canada +1"),
	CapoVerde("Capo Verde +238"),
	Ciad("Ciad +235"),
	Cile("Cile +56"),
	Cina("Cina +86"),
	Cipro("Cipro +357"),
	Colombia("Colombia +57"),
	Comore("Comore +269"),
	Congo("Congo +242"),
	Cook("Cook +682"),
	CoreadelNord("Corea del Nord +850"),
	CoreadelSud("Corea del Sud +82"),
	CostadAvorio("Costa d’Avorio +225"),
	Costarica("Costarica +506"),
	Croazia("Croazia +385"),
	Cuba("Cuba +53"),
	Danimarca("Danimarca +45"),
	DiegoGarcia("Diego Garcia +246"),
	Dominica("Dominica +1"),
	Ecuador("Ecuador +593"),
	Egitto("Egitto +20"),
	ElSalvador("El Salvador +503"),
	EmiratiArabiUniti("Emirati Arabi Uniti +971"),
	Eritrea("Eritrea +291"),
	Estonia("Estonia +372"),
	Etiopia("Etiopia +251"),
	FederazioneRussa("Federazione Russa +7"),
	Figi("Figi +679"),
	Filippine("Filippine +63"),
	Finlandia("Finlandia +358"),
	Francia("Francia +33"),
	Gabon("Gabon +241"),
	Gambia("Gambia +220"),
	Georgia("Georgia +995"),
	Germania("Germania +49"),
	Ghana("Ghana +233"),
	Giamaica("Giamaica +1"),
	Giappone("Giappone +81"),
	Gibilterra("Gibilterra +350"),
	Gibuti("Gibuti +253"),
	Giordania("Giordania +962"),
	GranBretagna("Gran Bretagna +44"),
	Grecia("Grecia +30"),
	Grenada("Grenada +1"),
	Groenlandia("Groenlandia +299"),
	Guadalupa("Guadalupa +590"),
	Guam("Guam +671"),
	Guatemala("Guatemala +502"),
	Guinea("Guinea +224"),
	GuineaBissau("Guinea Bissau +245"),
	GuineaEcuatoriale("Guinea Ecuatoriale +240"),
	Guyana("Guyana +592"),
	GuyanaFrancese("Guyana Francese +594"),
	Haiti("Haiti +509"),
	Honduras("Honduras +504"),
	HongKong("Hong Kong +852"),
	India("India +91"),
	Indonesia("Indonesia +62"),
	Iran("Iran +98"),
	Iraq("Iraq +964"),
	Irlanda("Irlanda +353"),
	Islanda("Islanda +354"),
	IsoleCayman("Isole Cayman +1"),
	IsoleFalkland("Isole Falkland +500"),
	IsoleFærOer("Isole Fær Oer +298"),
	IsoleMarianne("Isole Marianne +670"),
	IsoleMarshall("Isole Marshall +692"),
	IsoleNorfolk("Isole Norfolk +672"),
	IsoleSalomone("Isole Salomone +677"),
	IsoleVerginiGBR("Isole Vergini GBR) +1"),
	IsoleVerginiUS("Isole Vergini U.S.) +1"),
	Israele("Israele +972"),
	Italia("Italia +39"),
	Kazakistan("Kazakistan +996"),
	Kenia("Kenia +254"),
	Kirghizstan("Kirghizstan +996"),
	Kiribati("Kiribati +686"),
	Kuwait("Kuwait +965"),
	Laos("Laos +856"),
	Lesotho("Lesotho +266"),
	Lettonia("Lettonia +371"),
	Libano("Libano +961"),
	Liberia("Liberia +231"),
	Libia("Libia +218"),
	Liechtenstein("Liechtenstein +423"),
	Lituania("Lituania +370"),
	Lussemburgo("Lussemburgo +352"),
	Macao("Macao +853"),
	Macedonia("Macedonia +389"),
	Madagascar("Madagascar +261"),
	Malawi("Malawi +265"),
	Maldive("Maldive +960"),
	Malesia("Malesia +60"),
	Mali("Mali +223"),
	Malta("Malta +356"),
	Marocco("Marocco +212"),
	Martinica("Martinica +596"),
	Mauritania("Mauritania +222"),
	Mauritius("Mauritius +230"),
	Messico("Messico +52"),
	Moldavia("Moldavia +373"),
	MonacoPrincipatodi("Monaco Principato di +377"),
	Mongolia("Mongolia +976"),
	Montserrat("Montserrat +1"),
	Mozambico("Mozambico +258"),
	Namibia("Namibia +264"),
	Nepal("Nepal +977"),
	Nicaragua("Nicaragua +505"),
	Nigeria("Nigeria +234"),
	Niue("Niue +683"),
	Norvegia("Norvegia +47"),
	NuovaCaledonia("Nuova Caledonia +687"),
	NuovaZelanda("Nuova Zelanda +64"),
	Oman("Oman +968"),
	PaesiBassiOlanda("Paesi Bassi Olanda +31"),
	Pakistan("Pakistan +92"),
	Palau("Palau +680"),
	Panama("Panama +507"),
	PapuaNuovaGuinea("Papua Nuova Guinea +675"),
	Paraguay("Paraguay +595"),
	Perù("Perù +51"),
	PolinesiaFrancese("Polinesia Francese +689"),
	Polonia("Polonia +48"),
	Portogallo("Portogallo +351"),
	PortoRico("Porto Rico +1"),
	Qatar("Qatar +974"),
	RepCeca("Rep. Ceca +420"),
	RepCentrafrica("Rep. Centrafrica +236"),
	RepDemocraticadelCongo("Rep. Democratica del Congo +243"),
	RepDominicana("Rep. Dominicana +1"),
	ReunionFrancia("Reunion Francia +262"),
	Romania("Romania +40"),
	Ruanda("Ruanda +250"),
	SaintElena("Saint Elena +290"),
	SaintKittseNevis("Saint Kitts e Nevis +1"),
	SaintPierreeMiquelon("Saint Pierre e Miquelon +508"),
	SaintVincent("Saint Vincent +1"),
	SamoaAmericane("Samoa Americane +684"),
	SamoaOccidentale("Samoa Occidentale +685"),
	SantaLucia("Santa Lucia +1"),
	SaoTomèePrincipe("Sao Tomè e Principe +239"),
	Senegal("Senegal +221"),
	Seychelles("Seychelles +248"),
	SierraLeone("Sierra Leone +232"),
	Singapore("Singapore +65"),
	Siria("Siria +963"),
	Slovacchia("Slovacchia +421"),
	Slovenia("Slovenia +386"),
	Somalia("Somalia +252"),
	Spagna("Spagna +34"),
	SriLanka("Sri Lanka +94"),
	Sudafrica("Sudafrica +27"),
	Sudan("Sudan +249"),
	Svezia("Svezia +46"),
	Svizzera("Svizzera +41"),
	Swaziland("Swaziland +268"),
	Tajikistan("Tajikistan +737"),
	Taiwan("Taiwan +886"),
	Tanzania("Tanzania +255"),
	Thailandia("Thailandia +66"),
	Togo("Togo +228"),
	Tonga("Tonga +676"),
	TrinidadeTobago("Trinidad e Tobago +1"),
	Tunisia("Tunisia +216"),
	Turchia("Turchia +90"),
	Turkmenistan("Turkmenistan +993"),
	TurkseCaicos("Turks e Caicos +1"),
	Tuvalu("Tuvalu +688"),
	Ucraina("Ucraina +380"),
	Uganda("Uganda +256"),
	Ungheria("Ungheria +36"),
	Uruguay("Uruguay +598"),
	USA("USA +1"),
	Uzbekistan("Uzbekistan +998"),
	Vanuato("Vanuato +678"),
	Venezuela("Venezuela +58"),
	Vietnam("Vietnam +84"),
	WalliseFutuna("Wallis e Futuna +681"),
	Yemen("Yemen +967"),
	Yugoslavia("Yugoslavia +381"),
	Zambia("Zambia +260"),
	Zimbabwe("Zimbabwe +263");

	private String  prefisso;
    EnumPrefissoNumero(String prefisso) {
    	this.prefisso = prefisso;
	}



    public String getPrefisso() {
        return prefisso;
    }
}